"use client"

interface SlideRendererProps {
  htmlContent: string
}

export function SlideRenderer({ htmlContent }: SlideRendererProps) {
  return (
    // biome-ignore lint/security/noDangerouslySetInnerHtml: HTML content is generated by AI and stored securely
    <div className="presentation-slide h-full w-full" dangerouslySetInnerHTML={{ __html: htmlContent }} />
  )
}
