CREATE TABLE "slider-omni_llm_provider" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "slider-omni_llm_provider_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"provider" varchar(32) NOT NULL,
	"apiKey" varchar(512) NOT NULL,
	"baseUrl" varchar(512),
	"model" varchar(128),
	"azureEndpoint" varchar(512),
	"azureDeploymentName" varchar(256),
	"azureApiVersion" varchar(64),
	"isActive" boolean DEFAULT false NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "slider-omni_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "slider-omni_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "slider-omni_presentation" (
	"id" varchar(128) PRIMARY KEY NOT NULL,
	"title" varchar(256),
	"description" text,
	"html" text,
	"slideCount" integer,
	"slides" text,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "slider-omni_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "slider-omni_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"username" varchar(64) NOT NULL,
	"passwordHash" varchar(256) NOT NULL,
	"salt" varchar(64) NOT NULL,
	"permissions" text DEFAULT '{}' NOT NULL,
	"omnitokens" integer DEFAULT 10 NOT NULL,
	"omnicoins" integer DEFAULT 45 NOT NULL,
	"lastReset" timestamp with time zone NOT NULL,
	"createdAt" timestamp with time zone NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "llm_provider_idx" ON "slider-omni_llm_provider" USING btree ("provider");--> statement-breakpoint
CREATE UNIQUE INDEX "llm_provider_provider_unique" ON "slider-omni_llm_provider" USING btree ("provider");--> statement-breakpoint
CREATE INDEX "name_idx" ON "slider-omni_post" USING btree ("name");--> statement-breakpoint
CREATE INDEX "presentation_created_idx" ON "slider-omni_presentation" USING btree ("createdAt");--> statement-breakpoint
CREATE UNIQUE INDEX "user_username_unique" ON "slider-omni_user" USING btree ("username");