"use client"

import React, { use, useEffect, useState } from "react"
import { SlideNavigation } from "~/app/_components/presentations/slide-navigation"
import { Loader2 } from "lucide-react"

interface Slide {
  id: string
  title: string
  htmlContent: string
  order: number
}

interface Presentation {
  id: string
  title: string
  description?: string
  slides: Slide[]
  createdAt: Date
}

export default function PresentationPage({
  params,
}: {
  params: Promise<{ id: string }>
}) {
  const { id } = use(params)
  const [presentation, setPresentation] = useState<Presentation | null>(null)
  const [currentSlide, setCurrentSlide] = useState(1)
  const [isLoading, setIsLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const fetchPresentation = async () => {
      try {
        const response = await fetch(`/api/presentations/${id}`)
        if (!response.ok) {
          throw new Error("Presentation not found")
        }
        const data = await response.json()
        setPresentation(data)
      } catch (err) {
        setError(err instanceof Error ? err.message : "Failed to load presentation")
      } finally {
        setIsLoading(false)
      }
    }

    fetchPresentation()
  }, [id])

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (!presentation) return

      if (e.key === "ArrowRight" && currentSlide < presentation.slides.length) {
        setCurrentSlide((prev: number) => prev + 1)
      } else if (e.key === "ArrowLeft" && currentSlide > 1) {
        setCurrentSlide((prev: number) => prev - 1)
      }
    }

    window.addEventListener("keydown", handleKeyDown)
    return () => window.removeEventListener("keydown", handleKeyDown)
  }, [currentSlide, presentation])

  if (isLoading) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background">
        <div className="text-center">
          <Loader2 className="mx-auto mb-4 h-8 w-8 animate-spin text-primary" />
          <p className="text-muted-foreground">Carregando apresentação...</p>
        </div>
      </div>
    )
  }

  if (error || !presentation) {
    return (
      <div className="flex min-h-screen items-center justify-center bg-background">
        <div className="text-center">
          <h1 className="mb-2 text-2xl font-bold">Apresentação não encontrada</h1>
          <p className="mb-4 text-muted-foreground">{error ?? "A apresentação solicitada não existe."}</p>
          <a href="/" className="text-primary hover:underline">
            Voltar para o início
          </a>
        </div>
      </div>
    )
  }

  const currentSlideData = presentation.slides.find((s: Slide) => s.order === currentSlide)

  return (
    <div className="min-h-screen bg-background">
      {/* Slide Content */}
      <div className="h-screen w-full pb-20">
        {currentSlideData && (
          // biome-ignore lint/security/noDangerouslySetInnerHtml: HTML content is generated by AI and stored securely
          <div className="h-full w-full" dangerouslySetInnerHTML={{ __html: currentSlideData.htmlContent }} />
        )}
      </div>

      {/* Navigation */}
      <SlideNavigation
        currentSlide={currentSlide}
        totalSlides={presentation.slides.length}
        onPrevious={() => setCurrentSlide((prev: number) => Math.max(1, prev - 1))}
        onNext={() => setCurrentSlide((prev: number) => Math.min(presentation.slides.length, prev + 1))}
        presentationTitle={presentation.title}
      />
    </div>
  )
}
